version: 0.2

phases:
  pre_build:
    commands:
    - echo Run 'build / lint / test'
    - docker build -t sdk-js . 
    - docker run sdk-js yarn build
    - docker run sdk-js yarn lint
    - docker run sdk-js yarn testCI
    - echo 'build / lint / test' successful!  
  build:
    commands:
    - echo Build started on `date`, afterwards pushing to NPM registry https://www.npmjs.com/org/kiltprotocol
    - docker run -e NPM_USER='kiltbot' -e NPM_PASS="${NPM_PASS}" -e NPM_EMAIL='bot@kilt-protocol.io' -e NPM_SCOPE='@kiltprotocol' -e NPM_RC_FILE='./.npmrc' sdk-js yarn buildAndPublish
    - echo Build and publish completed on `date`
