module.exports = {
  exclude: ['**/*spec.ts', './src/index.ts', './src/wasm/wasm_exec.js'],
  listInvalidSymbolLinks: true,
  stripInternal: true,
  excludeNotExported: true,
  excludePrivate: true,
  hideGenerator: true,
  mode: 'file',
  tsconfig: 'tsconfig.json',
  readme: 'README.md',
  categorizeByGroup: true,
  toc: [
    'Blockchain',
    'Claimer',
    'Credential',
    'Attester',
    'Accumulator',
    'Verifier',
    'CombinedRequestBuilder',
    'requestPresentation',
    'verifyPresentation',
    'requestCombinedPresentation',
    'verifyCombinedPresentation',
  ],
}
